#pragma once

enum BehaviorEventEnum {
    BEHAVIOR_EVENT_NIL,
    BEHAVIOR_EVENT_MOVE,
    BEHAVIOR_EVENT_ATTACK,
    BEHAVIOR_EVENT_DAMAGE,
    BEHAVIOR_EVENT_LOOT,
    BEHAVIOR_EVENT_DEATH,
    BEHAVIOR_EVENT_PICKPOCKET,
    BEHAVIOR_EVENT_DEPOSIT,
    BEHAVIOR_EVENT_ACT,
    BEHAVIOR_EVENT_COUNT
};
