#pragma once

#include <ostream>
#include <string>

#define BEHAVIOR_DECL(name_) BEHAVIOR_##name_,
#define BEHAVIOR_ON_MOVE_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_MOVE_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_MOVE_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_ATTACK_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_ATTACK_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_ATTACK_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_DAMAGE_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_DAMAGE_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_DAMAGE_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_LOOT_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_LOOT_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_LOOT_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_DEATH_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_DEATH_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_DEATH_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_PICKPOCKET_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_PICKPOCKET_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_PICKPOCKET_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_DEPOSIT_AS_ACTOR_DECL(config_)
#define BEHAVIOR_ON_DEPOSIT_AS_TARGET_DECL(config_)
#define BEHAVIOR_ON_DEPOSIT_AS_OBSERVER_DECL(config_)
#define BEHAVIOR_ON_ACT_DECL(config_)
#define BEHAVIOR_PROPOSER_DECL(type_)
enum BehaviorEnum : int {
#include "Behavior.enum"
    BEHAVIOR_COUNT
};
#undef BEHAVIOR_DECL
#undef BEHAVIOR_ON_MOVE_AS_ACTOR_DECL
#undef BEHAVIOR_ON_MOVE_AS_TARGET_DECL
#undef BEHAVIOR_ON_MOVE_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_ATTACK_AS_ACTOR_DECL
#undef BEHAVIOR_ON_ATTACK_AS_TARGET_DECL
#undef BEHAVIOR_ON_ATTACK_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_DAMAGE_AS_ACTOR_DECL
#undef BEHAVIOR_ON_DAMAGE_AS_TARGET_DECL
#undef BEHAVIOR_ON_DAMAGE_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_LOOT_AS_ACTOR_DECL
#undef BEHAVIOR_ON_LOOT_AS_TARGET_DECL
#undef BEHAVIOR_ON_LOOT_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_DEATH_AS_ACTOR_DECL
#undef BEHAVIOR_ON_DEATH_AS_TARGET_DECL
#undef BEHAVIOR_ON_DEATH_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_PICKPOCKET_AS_ACTOR_DECL
#undef BEHAVIOR_ON_PICKPOCKET_AS_TARGET_DECL
#undef BEHAVIOR_ON_PICKPOCKET_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_DEPOSIT_AS_ACTOR_DECL
#undef BEHAVIOR_ON_DEPOSIT_AS_TARGET_DECL
#undef BEHAVIOR_ON_DEPOSIT_AS_OBSERVER_DECL
#undef BEHAVIOR_ON_ACT_DECL
#undef BEHAVIOR_PROPOSER_DECL

const char* behavior_to_text(int);

inline std::ostream& operator<<(std::ostream& os, BehaviorEnum b) {
    return os << behavior_to_text(b);
}
