#pragma once

enum AnimationType {
    ANIMATION_TYPE_NIL,
    ANIMATION_TYPE_IS_TRANSLATING,
    ANIMATION_TYPE_IS_TRANSITIONING,
    ANIMATION_TYPE_IS_GLYPHING,
    ANIMATION_TYPE_IS_REVERSIBLE,
    ANIMATION_TYPE_IS_OVERLAY,
    ANIMATION_TYPE_COUNT
};